server:
  servlet:
    context-path: /MX

Mydir:
  serverURI: C:\tomcat_media\webapps\walk_img/


getPic:
  serverURI: C:\tomcat_media\webapps\walk_img/

mybatis:
  type-aliases-package: com.walk.pojo
  mapper-locations: classpath:mapper/*.xml
  configuration:
    auto-mapping-behavior: full
    use-generated-keys: true


spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://111.230.232.46:3306/walk?useSSL=false
    username: root
    password: 1234

  jackson:
    date-format: yyyy-MM-dd HH:mm
    time-zone: GMT+8

#thymeleaf start
  thymeleaf:
    encoding: UTF-8
    #开发时关闭缓存,不然没法看到实时页面
    cache: false
    prefix: classpath:/templates/
    suffix: .html
#thymeleaf end

  resources:
    static-locations: classpath:/templates/,classpath:/templates/cpts_398_pn/
    add-mappings: true

  servlet:
    multipart:
      enabled: true
      max-file-size: 20Mb
      max-request-size: 50Mb


#pagehelper:
#    helperDialect: oracle
#    returnPageInfo: check
#    supportMethodsArguments: true
#    reasonable: true
#    params: count=countSql