server:
  servlet:
    context-path: /MX

Mydir:
  serverURI: C:\tomcat_media\webapps\walk_img/


getPic:
  serverURI: C:\tomcat_media\webapps\walk_img/

mybatis:
  type-aliases-package: com.walk.pojo
  mapper-locations: classpath:mapper/*.xml
  configuration:
    auto-mapping-behavior: full
    use-generated-keys: true


spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://111.230.232.46:3306/walk?useSSL=false
    username: root
    password: z@2418
# Redis数据库
  redis:
    database: 0
    host: 111.230.232.46
    port: 6379
    password: 2418
    timeout: 60s
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
        max-wait: -1

  jackson:
    date-format: yyyy-MM-dd HH:mm
    time-zone: GMT+8

#thymeleaf start
  thymeleaf:
    encoding: UTF-8
    #开发时关闭缓存,不然没法看到实时页面
    cache: false
    prefix: classpath:/templates/
    suffix: .html
#thymeleaf end

  resources:
    static-locations: classpath:/templates/,classpath:/templates/cpts_398_pn/,classpath:/templates/center/,classpath:/templates/login/,classpath:/templates/alert/,classpath:/templates/order/
    add-mappings: true

  servlet:
    multipart:
      enabled: true
      max-file-size: 20Mb
      max-request-size: 50Mb


pagehelper:
    helperDialect: mysql
    returnPageInfo: check
    supportMethodsArguments: true
    reasonable: true
    params: count=countSql
